// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// GetRequest is sent from a client to the server to read a value for a key
type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// GetReply is a response from the server to the client with the value
type GetReply struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Key     string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value   []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Error   string `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// PutRequest is sent from a client to the server to put a value for a key
type PutRequest struct {
	Key             string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value           []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TrackVisibility bool   `protobuf:"varint,3,opt,name=trackVisibility" json:"trackVisibility,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutRequest) GetTrackVisibility() bool {
	if m != nil {
		return m.TrackVisibility
	}
	return false
}

// PutReply is a response from the leader to the client
type PutReply struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Error   string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *PutReply) Reset()                    { *m = PutReply{} }
func (m *PutReply) String() string            { return proto.CompactTextString(m) }
func (*PutReply) ProtoMessage()               {}
func (*PutReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PutReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PutReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "rpc.GetRequest")
	proto.RegisterType((*GetReply)(nil), "rpc.GetReply")
	proto.RegisterType((*PutRequest)(nil), "rpc.PutRequest")
	proto.RegisterType((*PutReply)(nil), "rpc.PutReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Storage service

type StorageClient interface {
	GetValue(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	PutValue(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) GetValue(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/rpc.Storage/GetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) PutValue(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := grpc.Invoke(ctx, "/rpc.Storage/PutValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Storage service

type StorageServer interface {
	GetValue(context.Context, *GetRequest) (*GetReply, error)
	PutValue(context.Context, *PutRequest) (*PutReply, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Storage/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetValue(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_PutValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).PutValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Storage/PutValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).PutValue(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _Storage_GetValue_Handler,
		},
		{
			MethodName: "PutValue",
			Handler:    _Storage_PutValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xb7, 0x76, 0x73, 0xf5, 0xe1, 0x98, 0x04, 0x0f, 0xc1, 0x83, 0x8c, 0x9c, 0x7a, 0x90,
	0x1e, 0xf4, 0x8f, 0xf0, 0x3a, 0x22, 0xec, 0x28, 0x74, 0xe1, 0x29, 0x61, 0xc5, 0xc4, 0x97, 0xa4,
	0x50, 0xf0, 0x8f, 0x97, 0xa6, 0xeb, 0xd2, 0x09, 0x7a, 0xeb, 0xf7, 0xde, 0xd7, 0xef, 0xbd, 0xdf,
	0x0b, 0xac, 0x1d, 0x52, 0xab, 0x15, 0x56, 0x96, 0x8c, 0x37, 0x2c, 0x27, 0xab, 0xc4, 0x03, 0xc0,
	0x0b, 0x7a, 0x89, 0x5f, 0x01, 0x9d, 0x67, 0xb7, 0x90, 0x1f, 0xb1, 0xe3, 0xf3, 0xed, 0xbc, 0xbc,
	0x96, 0xfd, 0xa7, 0xf8, 0x86, 0x22, 0xf6, 0x6d, 0xd3, 0x31, 0x0e, 0x2b, 0x17, 0x94, 0x42, 0xe7,
	0xa2, 0xa3, 0x90, 0xa3, 0xec, 0x3b, 0x2d, 0x92, 0xd3, 0xe6, 0x93, 0x67, 0xf1, 0xdf, 0x51, 0x8e,
	0x89, 0xf9, 0x39, 0x91, 0xdd, 0xc1, 0xb2, 0xad, 0x9b, 0x80, 0x7c, 0xb1, 0x9d, 0x97, 0x37, 0x72,
	0x10, 0x7d, 0x15, 0x89, 0x0c, 0xf1, 0x65, 0x74, 0x0e, 0x42, 0xbc, 0x01, 0xec, 0xc2, 0xdf, 0xdb,
	0xa5, 0xac, 0x6c, 0x9a, 0x55, 0xc2, 0xc6, 0x53, 0xad, 0x8e, 0x7b, 0xed, 0xf4, 0x41, 0x37, 0xda,
	0x0f, 0xf3, 0x0b, 0xf9, 0xbb, 0x2c, 0xde, 0xa1, 0x88, 0xf9, 0xff, 0xd3, 0x9d, 0xe6, 0x66, 0x69,
	0xee, 0x84, 0x37, 0xbf, 0xe4, 0x3d, 0x73, 0x2c, 0x26, 0x1c, 0x4f, 0x08, 0xab, 0x57, 0x6f, 0xa8,
	0xfe, 0x40, 0xf6, 0x18, 0x0f, 0xba, 0x8f, 0x8b, 0x6e, 0x2a, 0xb2, 0xaa, 0x4a, 0xf7, 0xbf, 0x5f,
	0xa7, 0x82, 0x6d, 0x3a, 0x31, 0xeb, 0xdd, 0xbb, 0x70, 0xe1, 0x4e, 0xf7, 0x38, 0xb9, 0x47, 0x00,
	0x31, 0x3b, 0x5c, 0xc5, 0x87, 0x7d, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x36, 0x3a, 0x3a,
	0xe9, 0x01, 0x00, 0x00,
}
